tbd, ci-expected-results are run again after a pause if they fail the first time

diff --git a/bin/ci-import b/bin/ci-import
--- a/bin/ci-import
+++ b/bin/ci-import
@@ -17,5 +17,13 @@ echo "Starting import"
 echo "Finished launching import"
 
 . bin/ci-wait-steady-state
-. bin/ci-expected-results
+./bin/ci-expected-results || {
+    echo "-----"
+
+    echo "failed expected results. pausing and trying again"
+    
+    sleep 5
+    
+    ./bin/ci-expected-results
+}
 . bin/ci-performance
