Better error message on no workers being present

diff --git a/bin/wait-for-empty-gearman-queue b/bin/wait-for-empty-gearman-queue
--- a/bin/wait-for-empty-gearman-queue
+++ b/bin/wait-for-empty-gearman-queue
@@ -8,12 +8,13 @@ if [ -z "$environment" ]; then
 fi;
 
 while true; do
-    workers=$(pgrep -cf gearman:worker)
+    # `|| true` avoid failing the script when there are no results
+    workers=$(pgrep -cf gearman:worker || true)
+    watches=$(pgrep -cf queue:watch || true)
     if [ "$workers" -eq "0" ]; then
         echo "No alive gearman:worker processes, failing"
         break
     fi
-    watches=$(pgrep -cf queue:watch)
     if [ "$watches" -eq "0" ]; then
         echo "No alive queue:watch processes, failing"
         break
